{
	"version": 1735029208,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/1920x-sheet0.png",
		"images/1920x-sheet1.png",
		"images/blackdot0ff1f-sheet0.png",
		"images/sprite-sheet0.png",
		"images/particles.png",
		"images/asset14x-sheet0.png",
		"images/asset14x-sheet1.png",
		"images/asset14x-sheet2.png",
		"images/asset14x-sheet3.png",
		"images/asset14x-sheet4.png",
		"images/asset14x-sheet5.png",
		"images/slickerthanaverage_road_and_city_to_vegas_2d_cartoon_style_a54258c7096142689bfe04d83ae768bb-sheet0.png",
		"images/hillbilly-sheet0.png",
		"images/wegotem-sheet0.png",
		"images/droneshoothowto-sheet0.png",
		"images/droneshoothowto-sheet1.png",
		"images/play-sheet0.png",
		"media/get er done.m4a",
		"media/get er done.ogg",
		"media/sir yes sir.m4a",
		"media/sir yes sir.ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/shoot-6-81136.m4a",
		"media/shoot-6-81136.ogg",
		"media/drone shoot bgm.m4a",
		"media/drone shoot bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}