{
	"version": 1735804639,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/drone-sheet0.png",
		"images/drone-sheet1.png",
		"images/blackdot0ff1f-sheet0.png",
		"images/sprite-sheet0.png",
		"images/smoke.png",
		"images/explosion-sheet0.png",
		"images/explosion-sheet1.png",
		"images/explosion-sheet2.png",
		"images/explosion-sheet3.png",
		"images/explosion-sheet4.png",
		"images/explosion-sheet5.png",
		"images/slickerthanaverage_road_and_city_to_vegas_2d_cartoon_style_a54258c7096142689bfe04d83ae768bb-sheet0.png",
		"images/hillbilly-sheet0.png",
		"images/wegotem-sheet0.png",
		"images/droneshoothowto-sheet0.png",
		"images/droneshoothowto-sheet1.png",
		"images/play-sheet0.png",
		"images/flyingeaglesilhouette-sheet0.png",
		"images/flyingeaglesilhouette-sheet1.png",
		"images/particles.png",
		"media/get er done.m4a",
		"media/get er done.ogg",
		"media/explosion.m4a",
		"media/explosion.ogg",
		"media/shoot-6-81136.m4a",
		"media/shoot-6-81136.ogg",
		"media/drone 1.m4a",
		"media/drone 1.ogg",
		"media/drone 2.m4a",
		"media/drone 2.ogg",
		"media/drone 3.m4a",
		"media/drone 3.ogg",
		"media/drone 4.m4a",
		"media/drone 4.ogg",
		"media/drone 5.m4a",
		"media/drone 5.ogg",
		"media/drone 6.m4a",
		"media/drone 6.ogg",
		"media/sir yes sir (1).m4a",
		"media/sir yes sir (1).ogg",
		"media/drone shoot bgm.m4a",
		"media/drone shoot bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}